/**
 * author:zhangjuntao
 * description:所有权限列表（增删改查、把资源添加到role或module）
 */
Ext.define('Ext.view.dataMaintenance.permission.ResourceList', {
    extend:'Ext.grid.Panel',
    alias:'widget.permissionResourceList',
    store:'Ext.store.dataMaintenance.Resources',
    title:'资源维护',
    autoScroll:true,
    columnLines:true,
    stripeRows:true, //每列是否是斑马线分开
    forceFit:true, //自动填充，即让所有列填充满gird宽度
//    enableDragDrop: true,
//    multiSelect:true, //可以多选
    autoHeight:true,
    requires:[
        'Ext.view.dataMaintenance.SystemType',
        'Ext.view.dataMaintenance.permission.AddResourceWindow',
        'Ext.view.dataMaintenance.permission.UpdateResourceWindow',
        'Ext.view.dataMaintenance.ResourceType'
    ],
    dockedItems:[
        {
            xtype:'toolbar',
            dock:'top',
            id:'searchResourceComponent',
            items:[
                {
                    xtype:"textfield",
                    emptyText:"roleName",
                    width:100,
                    id:'searchRoleName'
                },
                {
                    xtype:"textfield",
                    emptyText:"name",
                    width:100,
                    id:'searchResourceName'
                },
                {
                    xtype:"textfield",
                    emptyText:"value",
                    width:100,
                    id:'searchResourceValue'
                },
                {
                    xtype:"textfield",
                    emptyText:"memo",
                    width:100,
                    id:'searchResourceMemo'
                },
                {
                    width:80,
                    id:'searchSystemType',
                    xtype:"systemType"
                },
                {
                    width:80,
                    id:'searchResourceType',
                    xtype:"resourceType"
                },

                "-",
                {
                    text:"查询",
                    xtype:'button',
                    action:'search',
                    iconCls:"icon-search",
                    tooltip:"根据条件查询资源信息",
                    scope:this
                },

                "-",
                {
                    text:"刷新资源",
                    xtype:'button',
                    action:'refresh',
                    iconCls:"icon-refresh",
                    scope:this
                }
            ]
        },
        {
            dock:'bottom',
            xtype:'pagingtoolbar',
            store:'Ext.store.dataMaintenance.Resources',
            displayInfo:true
        },
        {
            xtype:'toolbar',
            items:[
                {
                    text:'新增资源',
                    xtype:'button',
                    action:'addResource',
                    scope:this,
                    iconCls:'icon-add'
                },
                '-',
                {
                    text:'删除资源',
                    xtype:'button',
                    id:'delResourceButton',
                    action:'delResource',
                    scope:this,
                    iconCls:'icon-del',
                    disabled:true
                },
                '-',
                {
                    text:'编辑资源',
                    xtype:'button',
                    id:'editResourceButton',
                    iconCls:'icon-edit',
                    action:'editResource',
                    scope:this,
                    disabled:true
                },
                '-',
                {
                    text:'被使用列表',
                    xtype:'button',
                    id:'resourceDetailsButton',
                    iconCls:'icon-cog_edit',
                    action:'resourceDetails',
                    scope:this,
                    disabled:true
                }, '-',
                {
                    text:'添加资源到该角色',
                    xtype:'button',
                    iconCls:'icon-add-p',
                    action:'addToRole',
                    scope:this,
                    disabled:true
                }
            ]
        }
    ],
    initComponent:function () {
        var me = this;
        Ext.apply(me, {
            columns:[
                {
                    header:'No.',
                    xtype:'rownumberer',
                    sortable:false,
                    width:30
                },
                {
                    header:'resourceId',
                    dataIndex:'resourceId',
                    width:70,
                    checked : false
                },
                {
                    header:'name',
                    dataIndex:'name'
                },
                {
                    header:'value',
                    dataIndex:'value'
                },
                {
                    header:'memo',
                    dataIndex:'memo'
                },
                {
                    header:'status',
                    dataIndex:'status'
                },
                {
                    header:'type',
                    dataIndex:'type'
                },
                {
                    header:'systemType',
                    dataIndex:'systemType'
                }
            ]
        });
        this.callParent(arguments);
    }
});
