Ext.define('Ext.view.sys.user.View', {
    extend:'Ext.tab.Panel',
    alias:'widget.sysuserview',
    forceFit:true,
    frame:true,
    autoHeight:true,
    autoScroll:true,
    requires:[
        "Ext.view.sys.user.UserList",
        "Ext.view.sys.department.DepartmentLeaders",
        "Ext.view.sys.department.DepartmentMembers",
        "Ext.store.sys.DepartmentDetails",
        'Ext.view.sys.department.Tree'
    ],
    items:[
        {
            title:'用户账号',
            xtype:"sysuserlist"
        },
        {
            title:'部门设置',
            layout:'border',
            bodyBorder:true,
            hideBorders:true,
            id:'departmentView',
            defaults:{
                collapsible:true,
                split:true,
                animFloat:false,
                autoHide:false,
                useSplitTips:true
            },
            items:[
                {
                    region:'west',
                    xtype:'departmentTree',
                    width:300,
                    collapsible:true,
                    split:true
                },
                {
                    hideHeaders:true,
                    preventHeader:true,
                    region:'center',
                    layout:'border',
                    defaults:{
                        collapsible:false,
                        split:true,
                        animFloat:false,
                        autoHide:false,
                        useSplitTips:true
                    },
                    items:[
                        {
                            xtype:"departmentLeaders",
                            region:'north',
                            height:150
                        },
                        {
                            xtype:"departmentMembers",
                            region:'center'
                        }
                    ]
                }
            ]
        }
    ],
    initComponent:function () {
        var me = this;

        me.callParent();
    }

});